name: Financial News Sentiment CI pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check formatting with black
        run: |
          echo "Checking code formatting with black..."
          black --check scripts tests notebooks

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q
